name: tracker
description: The app for tracking different time intervals

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - res/assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: res/assets/fonts/Montserrat-Regular.ttf
        - asset: res/assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: res/assets/fonts/Montserrat-Thin.ttf
          weight: 100